site:
  title: "IFREAD"
  description: "个人技术博客，分享编程、设计和思考"
  author: "IFREAD"
  email: "ifread@example.com"
  url: "https://ifread.example.com"
  logo: "/logo.svg"
  favicon: "/favicon.svg"

social:
  - name: "GitHub"
    url: "https://github.com/ifread"
    icon: "github"
  - name: "Twitter"
    url: "https://twitter.com/ifread"
    icon: "twitter"

analytics:
  googleAnalyticsId: "G-XXXXXXXXXX"